# 服务端口号
server:
  port: 8001

# 数据库地址
datasource:
  url: 172.27.25.195:3306/microservice01

spring:
  application:
    name: microservice-order # 对外暴露的服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 669988
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000
mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.itcodai.springcloud.entity
  # mapper映射文件位置
  #mapper-locations: - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范


